### ISSUE TITLE
Long user names are not displayed correctly in user panel

### ISSUE THREAD

**Issue by hakimio** [DevExpress/devextreme-angular-template#111]
Try using 15 character or longer user names in user panels to see the issue.

**Comment by hakimio** [comment]
CSS fix if someone needs it:
```css
    .user-name {
        font-size: 14px;
        color: $base-text-color;
        margin-left: 5px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        line-height: normal;
    }
```
